import React from 'react';

function LocalItem() {
    return([
        { "nome":"Aveiro : Águeda"},
        { "nome":"Aveiro : Albergaria-a-Velha"},
        { "nome":"Aveiro : Anadia"},
        { "nome":"Aveiro : Arouca"},
        { "nome":"Aveiro : Aveiro"},
        { "nome":"Aveiro : Castelo de Paiva"},
        { "nome":"Aveiro : Espinho"},
        { "nome":"Aveiro : Estarreja"},
        { "nome":"Aveiro : Santa Maria da Feira"},
        { "nome":"Aveiro : Ílhavo"},
        { "nome":"Aveiro : Mealhada"},
        { "nome":"Aveiro : Murtosa"},
        { "nome":"Aveiro : Oliveira de Azeméis"},
        { "nome":"Aveiro : Oliveira do Bairro"},
        { "nome":"Aveiro : Ovar"},
        { "nome":"Aveiro : São João da Madeira"},
        { "nome":"Aveiro : Sever do Vouga"},
        { "nome":"Aveiro : Vagos"},
        { "nome":"Aveiro : Vale de Cambra"},
        { "nome":"Beja : Aljustrel"},
        { "nome":"Beja : Almodôvar"},
        { "nome":"Beja : Alvito"},
        { "nome":"Beja : Barrancos"},
        { "nome":"Beja : Beja"},
        { "nome":"Beja : Castro Verde"},
        { "nome":"Beja : Cuba"},
        { "nome":"Beja : Ferreira do Alentejo"},
        { "nome":"Beja : Mértola"},
        { "nome":"Beja : Moura"},
        { "nome":"Beja : Odemira"},
        { "nome":"Beja : Ourique"},
        { "nome":"Beja : Serpa"},
        { "nome":"Beja : Vidigueira"},
        { "nome":"Braga : Amares"},
        { "nome":"Braga : Barcelos"},
        { "nome":"Braga : Braga"},
        { "nome":"Braga : Cabeceiras de Basto"},
        { "nome":"Braga : Celorico de Basto"},
        { "nome":"Braga : Esposende"},
        { "nome":"Braga : Fafe"},
        { "nome":"Braga : Guimarães"},
        { "nome":"Braga : Póvoa de Lanhoso"},
        { "nome":"Braga : Terras de Bouro"},
        { "nome":"Braga : Vieira do Minho"},
        { "nome":"Braga : Vila Nova de Famalicão"},
        { "nome":"Braga : Vila Verde"},
        { "nome":"Braga : Vizela"},
        { "nome":"Bragança : Alfândega da Fé"},
        { "nome":"Bragança : Bragança"},
        { "nome":"Bragança : Carrazeda de Ansiães"},
        { "nome":"Bragança : Freixo de Espada à Cinta"},
        { "nome":"Bragança : Macedo de Cavaleiros"},
        { "nome":"Bragança : Miranda do Douro"},
        { "nome":"Bragança : Mirandela"},
        { "nome":"Bragança : Mogadouro"},
        { "nome":"Bragança : Torre de Moncorvo"},
        { "nome":"Bragança : Vila Flor"},
        { "nome":"Bragança : Vimioso"},
        { "nome":"Bragança : Vinhais"},
        { "nome":"Castelo Branco : Belmonte"},
        { "nome":"Castelo Branco : Castelo Branco"},
        { "nome":"Castelo Branco : Covilhã"},
        { "nome":"Castelo Branco : Fundão"},
        { "nome":"Castelo Branco : Idanha-a-Nova"},
        { "nome":"Castelo Branco : Oleiros"},
        { "nome":"Castelo Branco : Penamacor"},
        { "nome":"Castelo Branco : Proença-a-Nova"},
        { "nome":"Castelo Branco : Sertã"},
        { "nome":"Castelo Branco : Vila de Rei"},
        { "nome":"Castelo Branco : Vila Velha de Ródão"},
        { "nome":"Coimbra : Arganil"},
        { "nome":"Coimbra : Cantanhede"},
        { "nome":"Coimbra : Coimbra"},
        { "nome":"Coimbra : Condeixa-a-Nova"},
        { "nome":"Coimbra : Figueira da Foz"},
        { "nome":"Coimbra : Góis"},
        { "nome":"Coimbra : Lousã"},
        { "nome":"Coimbra : Mira"},
        { "nome":"Coimbra : Miranda do Corvo"},
        { "nome":"Coimbra : Montemor-o-Velho"},
        { "nome":"Coimbra : Oliveira do Hospital"},
        { "nome":"Coimbra : Pampilhosa da Serra"},
        { "nome":"Coimbra : Penacova"},
        { "nome":"Coimbra : Penela"},
        { "nome":"Coimbra : Soure"},
        { "nome":"Coimbra : Tábua"},
        { "nome":"Coimbra : Vila Nova de Poiares"},
        { "nome":"Évora : Alandroal"},
        { "nome":"Évora : Arraiolos"},
        { "nome":"Évora : Borba"},
        { "nome":"Évora : Estremoz"},
        { "nome":"Évora : Évora"},
        { "nome":"Évora : Montemor-o-Novo"},
        { "nome":"Évora : Mora"},
        { "nome":"Évora : Mourão"},
        { "nome":"Évora : Portel"},
        { "nome":"Évora : Redondo"},
        { "nome":"Évora : Reguengos de Monsaraz"},
        { "nome":"Évora : Vendas Novas"},
        { "nome":"Évora : Viana do Alentejo"},
        { "nome":"Évora : Vila Viçosa"},
        { "nome":"Faro : Albufeira"},
        { "nome":"Faro : Alcoutim"},
        { "nome":"Faro : Aljezur"},
        { "nome":"Faro : Castro Marim"},
        { "nome":"Faro : Faro"},
        { "nome":"Faro : Lagoa"},
        { "nome":"Faro : Lagos"},
        { "nome":"Faro : Loulé"},
        { "nome":"Faro : Monchique"},
        { "nome":"Faro : Olhão"},
        { "nome":"Faro : Portimão"},
        { "nome":"Faro : São Brás de Alportel"},
        { "nome":"Faro : Silves"},
        { "nome":"Faro : Tavira"},
        { "nome":"Faro : Vila do Bispo"},
        { "nome":"Faro : Vila Real de Santo António"},
        { "nome":"Guarda : Aguiar da Beira"},
        { "nome":"Guarda : Almeida"},
        { "nome":"Guarda : Celorico da Beira"},
        { "nome":"Guarda : Figueira de Castelo Rodrigo"},
        { "nome":"Guarda : Fornos de Algodres"},
        { "nome":"Guarda : Gouveia"},
        { "nome":"Guarda : Guarda"},
        { "nome":"Guarda : Manteigas"},
        { "nome":"Guarda : Mêda"},
        { "nome":"Guarda : Pinhel"},
        { "nome":"Guarda : Sabugal"},
        { "nome":"Guarda : Seia"},
        { "nome":"Guarda : Trancoso"},
        { "nome":"Guarda : Vila Nova de Foz Côa"},
        { "nome":"Leiria : Alcobaça"},
        { "nome":"Leiria : Alvaiázere"},
        { "nome":"Leiria : Ansião"},
        { "nome":"Leiria : Batalha"},
        { "nome":"Leiria : Bombarral"},
        { "nome":"Leiria : Caldas da Rainha"},
        { "nome":"Leiria : Castanheira de Pêra"},
        { "nome":"Leiria : Figueiró dos Vinhos"},
        { "nome":"Leiria : Leiria"},
        { "nome":"Leiria : Marinha Grande"},
        { "nome":"Leiria : Nazaré"},
        { "nome":"Leiria : Óbidos"},
        { "nome":"Leiria : Pedrógão Grande"},
        { "nome":"Leiria : Peniche"},
        { "nome":"Leiria : Pombal"},
        { "nome":"Leiria : Porto de Mós"},
        { "nome":"Lisboa : Alenquer"},
        { "nome":"Lisboa : Arruda dos Vinhos"},
        { "nome":"Lisboa : Azambuja"},
        { "nome":"Lisboa : Cadaval"},
        { "nome":"Lisboa : Cascais"},
        { "nome":"Lisboa : Lisboa"},
        { "nome":"Lisboa : Loures"},
        { "nome":"Lisboa : Lourinhã"},
        { "nome":"Lisboa : Mafra"},
        { "nome":"Lisboa : Oeiras"},
        { "nome":"Lisboa : Sintra"},
        { "nome":"Lisboa : Sobral de Monte Agraço"},
        { "nome":"Lisboa : Torres Vedras"},
        { "nome":"Lisboa : Vila Franca de Xira"},
        { "nome":"Lisboa : Amadora"},
        { "nome":"Lisboa : Odivelas"},
        { "nome":"Portalegre : Alter do Chão"},
        { "nome":"Portalegre : Arronches"},
        { "nome":"Portalegre : Avis"},
        { "nome":"Portalegre : Campo Maior"},
        { "nome":"Portalegre : Castelo de Vide"},
        { "nome":"Portalegre : Crato"},
        { "nome":"Portalegre : Elvas"},
        { "nome":"Portalegre : Fronteira"},
        { "nome":"Portalegre : Gavião"},
        { "nome":"Portalegre : Marvão"},
        { "nome":"Portalegre : Monforte"},
        { "nome":"Portalegre : Nisa"},
        { "nome":"Portalegre : Ponte de Sor"},
        { "nome":"Portalegre : Portalegre"},
        { "nome":"Portalegre : Sousel"},
        { "nome":"Porto : Amarante"},
        { "nome":"Porto : Baião"},
        { "nome":"Porto : Felgueiras"},
        { "nome":"Porto : Gondomar"},
        { "nome":"Porto : Lousada"},
        { "nome":"Porto : Maia"},
        { "nome":"Porto : Marco de Canaveses"},
        { "nome":"Porto : Matosinhos"},
        { "nome":"Porto : Paços de Ferreira"},
        { "nome":"Porto : Paredes"},
        { "nome":"Porto : Penafiel"},
        { "nome":"Porto : Porto"},
        { "nome":"Porto : Póvoa de Varzim"},
        { "nome":"Porto : Santo Tirso"},
        { "nome":"Porto : Valongo"},
        { "nome":"Porto : Vila do Conde"},
        { "nome":"Porto : Vila Nova de Gaia"},
        { "nome":"Porto : Trofa"},
        { "nome":"Santarém : Abrantes"},
        { "nome":"Santarém : Alcanena"},
        { "nome":"Santarém : Almeirim"},
        { "nome":"Santarém : Alpiarça"},
        { "nome":"Santarém : Benavente"},
        { "nome":"Santarém : Cartaxo"},
        { "nome":"Santarém : Chamusca"},
        { "nome":"Santarém : Constância"},
        { "nome":"Santarém : Coruche"},
        { "nome":"Santarém : Entroncamento"},
        { "nome":"Santarém : Ferreira do Zêzere"},
        { "nome":"Santarém : Golegã"},
        { "nome":"Santarém : Mação"},
        { "nome":"Santarém : Rio Maior"},
        { "nome":"Santarém : Salvaterra de Magos"},
        { "nome":"Santarém : Santarém"},
        { "nome":"Santarém : Sardoal"},
        { "nome":"Santarém : Tomar"},
        { "nome":"Santarém : Torres Novas"},
        { "nome":"Santarém : Vila Nova da Barquinha"},
        { "nome":"Santarém : Ourém"},
        { "nome":"Setúbal : Alcácer do Sal"},
        { "nome":"Setúbal : Alcochete"},
        { "nome":"Setúbal : Almada"},
        { "nome":"Setúbal : Barreiro"},
        { "nome":"Setúbal : Grândola"},
        { "nome":"Setúbal : Moita"},
        { "nome":"Setúbal : Montijo"},
        { "nome":"Setúbal : Palmela"},
        { "nome":"Setúbal : Santiago do Cacém"},
        { "nome":"Setúbal : Seixal"},
        { "nome":"Setúbal : Sesimbra"},
        { "nome":"Setúbal : Setúbal"},
        { "nome":"Setúbal : Sines"},
        { "nome":"Viana do Castelo : Arcos de Valdevez"},
        { "nome":"Viana do Castelo : Caminha"},
        { "nome":"Viana do Castelo : Melgaço"},
        { "nome":"Viana do Castelo : Monção"},
        { "nome":"Viana do Castelo : Paredes de Coura"},
        { "nome":"Viana do Castelo : Ponte da Barca"},
        { "nome":"Viana do Castelo : Ponte de Lima"},
        { "nome":"Viana do Castelo : Valença"},
        { "nome":"Viana do Castelo : Viana do Castelo"},
        { "nome":"Viana do Castelo : Vila Nova de Cerveira"},
        { "nome":"Vila Real : Alijó"},
        { "nome":"Vila Real : Boticas"},
        { "nome":"Vila Real : Chaves"},
        { "nome":"Vila Real : Mesão Frio"},
        { "nome":"Vila Real : Mondim de Basto"},
        { "nome":"Vila Real : Montalegre"},
        { "nome":"Vila Real : Murça"},
        { "nome":"Vila Real : Peso da Régua"},
        { "nome":"Vila Real : Ribeira de Pena"},
        { "nome":"Vila Real : Sabrosa"},
        { "nome":"Vila Real : Santa Marta de Penaguião"},
        { "nome":"Vila Real : Valpaços"},
        { "nome":"Vila Real : Vila Pouca de Aguiar"},
        { "nome":"Vila Real : Vila Real"},
        { "nome":"Viseu : Armamar"},
        { "nome":"Viseu : Carregal do Sal"},
        { "nome":"Viseu : Castro Daire"},
        { "nome":"Viseu : Cinfães"},
        { "nome":"Viseu : Lamego"},
        { "nome":"Viseu : Mangualde"},
        { "nome":"Viseu : Moimenta da Beira"},
        { "nome":"Viseu : Mortágua"},
        { "nome":"Viseu : Nelas"},
        { "nome":"Viseu : Oliveira de Frades"},
        { "nome":"Viseu : Penalva do Castelo"},
        { "nome":"Viseu : Penedono"},
        { "nome":"Viseu : Resende"},
        { "nome":"Viseu : Santa Comba Dão"},
        { "nome":"Viseu : São João da Pesqueira"},
        { "nome":"Viseu : São Pedro do Sul"},
        { "nome":"Viseu : Sátão"},
        { "nome":"Viseu : Sernancelhe"},
        { "nome":"Viseu : Tabuaço"},
        { "nome":"Viseu : Tarouca"},
        { "nome":"Viseu : Tondela"},
        { "nome":"Viseu : Vila Nova de Paiva"},
        { "nome":"Viseu : Viseu"},
        { "nome":"Viseu : Vouzela"},
        { "nome":"Ilha da Madeira : Calheta"},
        { "nome":"Ilha da Madeira : Câmara de Lobos"},
        { "nome":"Ilha da Madeira : Funchal"},
        { "nome":"Ilha da Madeira : Machico"},
        { "nome":"Ilha da Madeira : Ponta do Sol"},
        { "nome":"Ilha da Madeira : Porto Moniz"},
        { "nome":"Ilha da Madeira : Ribeira Brava"},
        { "nome":"Ilha da Madeira : Santa Cruz"},
        { "nome":"Ilha da Madeira : Santana"},
        { "nome":"Ilha da Madeira : São Vicente"},
        { "nome":"Ilha de Porto Santo : Porto Santo"},
        { "nome":"Ilha de Santa Maria : Vila do Porto"},
        { "nome":"Ilha de São Miguel : Lagoa"},
        { "nome":"Ilha de São Miguel : Nordeste"},
        { "nome":"Ilha de São Miguel : Ponta Delgada"},
        { "nome":"Ilha de São Miguel : Povoação"},
        { "nome":"Ilha de São Miguel : Ribeira Grande"},
        { "nome":"Ilha de São Miguel : Vila Franca do Campo"},
        { "nome":"Ilha Terceira : Angra do Heroísmo"},
        { "nome":"Ilha Terceira : Vila da Praia da Vitória"},
        { "nome":"Ilha Graciosa : Santa Cruz da Graciosa"},
        { "nome":"Ilha de São Jorge : Calheta"},
        { "nome":"Ilha de São Jorge : Velas"},
        { "nome":"Ilha do Pico : Lajes do Pico"},
        { "nome":"Ilha do Pico : Madalena"},
        { "nome":"Ilha do Pico : São Roque do Pico"},
        { "nome":"Ilha do Faial : Horta"},
        { "nome":"Ilha das Flores : Lajes das Flores"},
        { "nome":"Ilha das Flores : Santa Cruz das Flores"},
        { "nome":"Ilha do Corvo : Corvo"}
        
    ]);

}

export default LocalItem;